class Country {
  final String name;
  final String iso;

  const Country({required this.name, required this.iso});
}

const List<Country> countries = [
  Country(name: 'Afghanistan', iso: 'AF'),
  Country(name: 'Albania', iso: 'AL'),
  Country(name: 'Algeria', iso: 'DZ'),
  Country(name: 'Andorra', iso: 'AD'),
  Country(name: 'Angola', iso: 'AO'),
  Country(name: 'Antigua and Barbuda', iso: 'AG'),
  Country(name: 'Argentina', iso: 'AR'),
  Country(name: 'Armenia', iso: 'AM'),
  Country(name: 'Australia', iso: 'AU'),
  Country(name: 'Austria', iso: 'AT'),
  Country(name: 'Azerbaijan', iso: 'AZ'),
  Country(name: 'Bahamas', iso: 'BS'),
  Country(name: 'Bahrain', iso: 'BH'),
  Country(name: 'Bangladesh', iso: 'BD'),
  Country(name: 'Barbados', iso: 'BB'),
  Country(name: 'Belarus', iso: 'BY'),
  Country(name: 'Belgium', iso: 'BE'),
  Country(name: 'Belize', iso: 'BZ'),
  Country(name: 'Benin', iso: 'BJ'),
  Country(name: 'Bhutan', iso: 'BT'),
  Country(name: 'Bolivia', iso: 'BO'),
  Country(name: 'Bosnia and Herzegovina', iso: 'BA'),
  Country(name: 'Botswana', iso: 'BW'),
  Country(name: 'Brazil', iso: 'BR'),
  Country(name: 'Brunei', iso: 'BN'),
  Country(name: 'Bulgaria', iso: 'BG'),
  Country(name: 'Burkina Faso', iso: 'BF'),
  Country(name: 'Burundi', iso: 'BI'),
  Country(name: 'Cambodia', iso: 'KH'),
  Country(name: 'Cameroon', iso: 'CM'),
  Country(name: 'Canada', iso: 'CA'),
  Country(name: 'Cape Verde', iso: 'CV'),
  Country(name: 'Central African Republic', iso: 'CF'),
  Country(name: 'Chad', iso: 'TD'),
  Country(name: 'Chile', iso: 'CL'),
  Country(name: 'China', iso: 'CN'),
  Country(name: 'Colombia', iso: 'CO'),
  Country(name: 'Comoros', iso: 'KM'),
  Country(name: 'Congo', iso: 'CG'),
  Country(name: 'Costa Rica', iso: 'CR'),
  Country(name: 'Croatia', iso: 'HR'),
  Country(name: 'Cuba', iso: 'CU'),
  Country(name: 'Cyprus', iso: 'CY'),
  Country(name: 'Czech Republic', iso: 'CZ'),
  Country(name: 'Denmark', iso: 'DK'),
  Country(name: 'Djibouti', iso: 'DJ'),
  Country(name: 'Dominica', iso: 'DM'),
  Country(name: 'Dominican Republic', iso: 'DO'),
  Country(name: 'Ecuador', iso: 'EC'),
  Country(name: 'Egypt', iso: 'EG'),
  Country(name: 'El Salvador', iso: 'SV'),
  Country(name: 'Equatorial Guinea', iso: 'GQ'),
  Country(name: 'Eritrea', iso: 'ER'),
  Country(name: 'Estonia', iso: 'EE'),
  Country(name: 'Eswatini', iso: 'SZ'),
  Country(name: 'Ethiopia', iso: 'ET'),
  Country(name: 'Fiji', iso: 'FJ'),
  Country(name: 'Finland', iso: 'FI'),
  Country(name: 'France', iso: 'FR'),
  Country(name: 'Gabon', iso: 'GA'),
  Country(name: 'Gambia', iso: 'GM'),
  Country(name: 'Georgia', iso: 'GE'),
  Country(name: 'Germany', iso: 'DE'),
  Country(name: 'Ghana', iso: 'GH'),
  Country(name: 'Greece', iso: 'GR'),
  Country(name: 'Grenada', iso: 'GD'),
  Country(name: 'Guatemala', iso: 'GT'),
  Country(name: 'Guinea', iso: 'GN'),
  Country(name: 'Guinea-Bissau', iso: 'GW'),
  Country(name: 'Guyana', iso: 'GY'),
  Country(name: 'Haiti', iso: 'HT'),
  Country(name: 'Honduras', iso: 'HN'),
  Country(name: 'Hungary', iso: 'HU'),
  Country(name: 'Iceland', iso: 'IS'),
  Country(name: 'India', iso: 'IN'),
  Country(name: 'Indonesia', iso: 'ID'),
  Country(name: 'Iran', iso: 'IR'),
  Country(name: 'Iraq', iso: 'IQ'),
  Country(name: 'Ireland', iso: 'IE'),
  Country(name: 'Israel', iso: 'IL'),
  Country(name: 'Italy', iso: 'IT'),
  Country(name: 'Jamaica', iso: 'JM'),
  Country(name: 'Japan', iso: 'JP'),
  Country(name: 'Jordan', iso: 'JO'),
  Country(name: 'Kazakhstan', iso: 'KZ'),
  Country(name: 'Kenya', iso: 'KE'),
  Country(name: 'Kiribati', iso: 'KI'),
  Country(name: 'Kuwait', iso: 'KW'),
  Country(name: 'Kyrgyzstan', iso: 'KG'),
  Country(name: 'Laos', iso: 'LA'),
  Country(name: 'Latvia', iso: 'LV'),
  Country(name: 'Lebanon', iso: 'LB'),
  Country(name: 'Lesotho', iso: 'LS'),
  Country(name: 'Liberia', iso: 'LR'),
  Country(name: 'Libya', iso: 'LY'),
  Country(name: 'Liechtenstein', iso: 'LI'),
  Country(name: 'Lithuania', iso: 'LT'),
  Country(name: 'Luxembourg', iso: 'LU'),
  Country(name: 'Madagascar', iso: 'MG'),
  Country(name: 'Malawi', iso: 'MW'),
  Country(name: 'Malaysia', iso: 'MY'),
  Country(name: 'Maldives', iso: 'MV'),
  Country(name: 'Mali', iso: 'ML'),
  Country(name: 'Malta', iso: 'MT'),
  Country(name: 'Marshall Islands', iso: 'MH'),
  Country(name: 'Mauritania', iso: 'MR'),
  Country(name: 'Mauritius', iso: 'MU'),
  Country(name: 'Mexico', iso: 'MX'),
  Country(name: 'Micronesia', iso: 'FM'),
  Country(name: 'Moldova', iso: 'MD'),
  Country(name: 'Monaco', iso: 'MC'),
  Country(name: 'Mongolia', iso: 'MN'),
  Country(name: 'Montenegro', iso: 'ME'),
  Country(name: 'Morocco', iso: 'MA'),
  Country(name: 'Mozambique', iso: 'MZ'),
  Country(name: 'Myanmar', iso: 'MM'),
  Country(name: 'Namibia', iso: 'NA'),
  Country(name: 'Nauru', iso: 'NR'),
  Country(name: 'Nepal', iso: 'NP'),
  Country(name: 'Netherlands', iso: 'NL'),
  Country(name: 'New Zealand', iso: 'NZ'),
  Country(name: 'Nicaragua', iso: 'NI'),
  Country(name: 'Niger', iso: 'NE'),
  Country(name: 'Nigeria', iso: 'NG'),
  Country(name: 'North Korea', iso: 'KP'),
  Country(name: 'North Macedonia', iso: 'MK'),
  Country(name: 'Norway', iso: 'NO'),
  Country(name: 'Oman', iso: 'OM'),
  Country(name: 'Pakistan', iso: 'PK'),
  Country(name: 'Palau', iso: 'PW'),
  Country(name: 'Palestine', iso: 'PS'),
  Country(name: 'Panama', iso: 'PA'),
  Country(name: 'Papua New Guinea', iso: 'PG'),
  Country(name: 'Paraguay', iso: 'PY'),
  Country(name: 'Peru', iso: 'PE'),
  Country(name: 'Philippines', iso: 'PH'),
  Country(name: 'Poland', iso: 'PL'),
  Country(name: 'Portugal', iso: 'PT'),
  Country(name: 'Qatar', iso: 'QA'),
  Country(name: 'Romania', iso: 'RO'),
  Country(name: 'Russia', iso: 'RU'),
  Country(name: 'Rwanda', iso: 'RW'),
  Country(name: 'Saint Kitts and Nevis', iso: 'KN'),
  Country(name: 'Saint Lucia', iso: 'LC'),
  Country(name: 'Saint Vincent and the Grenadines', iso: 'VC'),
  Country(name: 'Samoa', iso: 'WS'),
  Country(name: 'San Marino', iso: 'SM'),
  Country(name: 'Sao Tome and Principe', iso: 'ST'),
  Country(name: 'Saudi Arabia', iso: 'SA'),
  Country(name: 'Senegal', iso: 'SN'),
  Country(name: 'Serbia', iso: 'RS'),
  Country(name: 'Seychelles', iso: 'SC'),
  Country(name: 'Sierra Leone', iso: 'SL'),
  Country(name: 'Singapore', iso: 'SG'),
  Country(name: 'Slovakia', iso: 'SK'),
  Country(name: 'Slovenia', iso: 'SI'),
  Country(name: 'Solomon Islands', iso: 'SB'),
  Country(name: 'Somalia', iso: 'SO'),
  Country(name: 'South Africa', iso: 'ZA'),
  Country(name: 'South Korea', iso: 'KR'),
  Country(name: 'South Sudan', iso: 'SS'),
  Country(name: 'Spain', iso: 'ES'),
  Country(name: 'Sri Lanka', iso: 'LK'),
  Country(name: 'Sudan', iso: 'SD'),
  Country(name: 'Suriname', iso: 'SR'),
  Country(name: 'Sweden', iso: 'SE'),
  Country(name: 'Switzerland', iso: 'CH'),
  Country(name: 'Syria', iso: 'SY'),
  Country(name: 'Taiwan', iso: 'TW'),
  Country(name: 'Tajikistan', iso: 'TJ'),
  Country(name: 'Tanzania', iso: 'TZ'),
  Country(name: 'Thailand', iso: 'TH'),
  Country(name: 'Timor-Leste', iso: 'TL'),
  Country(name: 'Togo', iso: 'TG'),
  Country(name: 'Tonga', iso: 'TO'),
  Country(name: 'Trinidad and Tobago', iso: 'TT'),
  Country(name: 'Tunisia', iso: 'TN'),
  Country(name: 'Turkey', iso: 'TR'),
  Country(name: 'Turkmenistan', iso: 'TM'),
  Country(name: 'Tuvalu', iso: 'TV'),
  Country(name: 'Uganda', iso: 'UG'),
  Country(name: 'Ukraine', iso: 'UA'),
  Country(name: 'United Arab Emirates', iso: 'AE'),
  Country(name: 'United Kingdom', iso: 'GB'),
  Country(name: 'United States', iso: 'US'),
  Country(name: 'Uruguay', iso: 'UY'),
  Country(name: 'Uzbekistan', iso: 'UZ'),
  Country(name: 'Vanuatu', iso: 'VU'),
  Country(name: 'Vatican City', iso: 'VA'),
  Country(name: 'Venezuela', iso: 'VE'),
  Country(name: 'Vietnam', iso: 'VN'),
  Country(name: 'Yemen', iso: 'YE'),
  Country(name: 'Zambia', iso: 'ZM'),
  Country(name: 'Zimbabwe', iso: 'ZW'),
];
