import 'dart:convert';

import 'package:opei/l10n/app_localizations.dart';

class Country {
  final String iso;

  const Country({required this.iso});
}

const List<Country> countries = [
  Country(iso: 'AF'),
  Country(iso: 'AL'),
  Country(iso: 'DZ'),
  Country(iso: 'AD'),
  Country(iso: 'AO'),
  Country(iso: 'AG'),
  Country(iso: 'AR'),
  Country(iso: 'AM'),
  Country(iso: 'AU'),
  Country(iso: 'AT'),
  Country(iso: 'AZ'),
  Country(iso: 'BS'),
  Country(iso: 'BH'),
  Country(iso: 'BD'),
  Country(iso: 'BB'),
  Country(iso: 'BY'),
  Country(iso: 'BE'),
  Country(iso: 'BZ'),
  Country(iso: 'BJ'),
  Country(iso: 'BT'),
  Country(iso: 'BO'),
  Country(iso: 'BA'),
  Country(iso: 'BW'),
  Country(iso: 'BR'),
  Country(iso: 'BN'),
  Country(iso: 'BG'),
  Country(iso: 'BF'),
  Country(iso: 'BI'),
  Country(iso: 'KH'),
  Country(iso: 'CM'),
  Country(iso: 'CA'),
  Country(iso: 'CV'),
  Country(iso: 'CF'),
  Country(iso: 'TD'),
  Country(iso: 'CL'),
  Country(iso: 'CN'),
  Country(iso: 'CO'),
  Country(iso: 'KM'),
  Country(iso: 'CG'),
  Country(iso: 'CR'),
  Country(iso: 'HR'),
  Country(iso: 'CU'),
  Country(iso: 'CY'),
  Country(iso: 'CZ'),
  Country(iso: 'DK'),
  Country(iso: 'DJ'),
  Country(iso: 'DM'),
  Country(iso: 'DO'),
  Country(iso: 'EC'),
  Country(iso: 'EG'),
  Country(iso: 'SV'),
  Country(iso: 'GQ'),
  Country(iso: 'ER'),
  Country(iso: 'EE'),
  Country(iso: 'SZ'),
  Country(iso: 'ET'),
  Country(iso: 'FJ'),
  Country(iso: 'FI'),
  Country(iso: 'FR'),
  Country(iso: 'GA'),
  Country(iso: 'GM'),
  Country(iso: 'GE'),
  Country(iso: 'DE'),
  Country(iso: 'GH'),
  Country(iso: 'GR'),
  Country(iso: 'GD'),
  Country(iso: 'GT'),
  Country(iso: 'GN'),
  Country(iso: 'GW'),
  Country(iso: 'GY'),
  Country(iso: 'HT'),
  Country(iso: 'HN'),
  Country(iso: 'HU'),
  Country(iso: 'IS'),
  Country(iso: 'IN'),
  Country(iso: 'ID'),
  Country(iso: 'IR'),
  Country(iso: 'IQ'),
  Country(iso: 'IE'),
  Country(iso: 'IL'),
  Country(iso: 'IT'),
  Country(iso: 'JM'),
  Country(iso: 'JP'),
  Country(iso: 'JO'),
  Country(iso: 'KZ'),
  Country(iso: 'KE'),
  Country(iso: 'KI'),
  Country(iso: 'KW'),
  Country(iso: 'KG'),
  Country(iso: 'LA'),
  Country(iso: 'LV'),
  Country(iso: 'LB'),
  Country(iso: 'LS'),
  Country(iso: 'LR'),
  Country(iso: 'LY'),
  Country(iso: 'LI'),
  Country(iso: 'LT'),
  Country(iso: 'LU'),
  Country(iso: 'MG'),
  Country(iso: 'MW'),
  Country(iso: 'MY'),
  Country(iso: 'MV'),
  Country(iso: 'ML'),
  Country(iso: 'MT'),
  Country(iso: 'MH'),
  Country(iso: 'MR'),
  Country(iso: 'MU'),
  Country(iso: 'MX'),
  Country(iso: 'FM'),
  Country(iso: 'MD'),
  Country(iso: 'MC'),
  Country(iso: 'MN'),
  Country(iso: 'ME'),
  Country(iso: 'MA'),
  Country(iso: 'MZ'),
  Country(iso: 'MM'),
  Country(iso: 'NA'),
  Country(iso: 'NR'),
  Country(iso: 'NP'),
  Country(iso: 'NL'),
  Country(iso: 'NZ'),
  Country(iso: 'NI'),
  Country(iso: 'NE'),
  Country(iso: 'NG'),
  Country(iso: 'KP'),
  Country(iso: 'MK'),
  Country(iso: 'NO'),
  Country(iso: 'OM'),
  Country(iso: 'PK'),
  Country(iso: 'PW'),
  Country(iso: 'PS'),
  Country(iso: 'PA'),
  Country(iso: 'PG'),
  Country(iso: 'PY'),
  Country(iso: 'PE'),
  Country(iso: 'PH'),
  Country(iso: 'PL'),
  Country(iso: 'PT'),
  Country(iso: 'QA'),
  Country(iso: 'RO'),
  Country(iso: 'RU'),
  Country(iso: 'RW'),
  Country(iso: 'KN'),
  Country(iso: 'LC'),
  Country(iso: 'VC'),
  Country(iso: 'WS'),
  Country(iso: 'SM'),
  Country(iso: 'ST'),
  Country(iso: 'SA'),
  Country(iso: 'SN'),
  Country(iso: 'RS'),
  Country(iso: 'SC'),
  Country(iso: 'SL'),
  Country(iso: 'SG'),
  Country(iso: 'SK'),
  Country(iso: 'SI'),
  Country(iso: 'SB'),
  Country(iso: 'SO'),
  Country(iso: 'ZA'),
  Country(iso: 'KR'),
  Country(iso: 'SS'),
  Country(iso: 'ES'),
  Country(iso: 'LK'),
  Country(iso: 'SD'),
  Country(iso: 'SR'),
  Country(iso: 'SE'),
  Country(iso: 'CH'),
  Country(iso: 'SY'),
  Country(iso: 'TW'),
  Country(iso: 'TJ'),
  Country(iso: 'TZ'),
  Country(iso: 'TH'),
  Country(iso: 'TL'),
  Country(iso: 'TG'),
  Country(iso: 'TO'),
  Country(iso: 'TT'),
  Country(iso: 'TN'),
  Country(iso: 'TR'),
  Country(iso: 'TM'),
  Country(iso: 'TV'),
  Country(iso: 'UG'),
  Country(iso: 'UA'),
  Country(iso: 'AE'),
  Country(iso: 'GB'),
  Country(iso: 'US'),
  Country(iso: 'UY'),
  Country(iso: 'UZ'),
  Country(iso: 'VU'),
  Country(iso: 'VA'),
  Country(iso: 'VE'),
  Country(iso: 'VN'),
  Country(iso: 'YE'),
  Country(iso: 'ZM'),
  Country(iso: 'ZW'),
];

final Map<String, Map<String, String>> _countryNamesCache =
    <String, Map<String, String>>{};

Map<String, String> _countryNames(AppLocalizations l10n) {
  return _countryNamesCache.putIfAbsent(l10n.localeName, () {
    final decodedText = utf8.decode(base64Decode(l10n.countryNamesBase64));
    final decoded = jsonDecode(decodedText);
    if (decoded is Map<String, dynamic>) {
      return decoded.map(
        (key, value) => MapEntry(key.toUpperCase(), value.toString()),
      );
    }
    return <String, String>{};
  });
}

String localizedCountryName(Country country, AppLocalizations l10n) {
  return _countryNames(l10n)[country.iso.toUpperCase()] ?? country.iso;
}

const Set<String> restrictedCountryIsoCodes = {
  'AF',
  'BY',
  'BI',
  'CF',
  'CG',
  'CU',
  'IR',
  'IQ',
  'LB',
  'LR',
  'LY',
  'MM',
  'NI',
  'KP',
  'PS',
  'RU',
  'SO',
  'SS',
  'SY',
  'UA',
  'VE',
  'YE',
  'ZW',
};

final List<Country> allowedCountries = countries
    .where((country) => !restrictedCountryIsoCodes.contains(country.iso))
    .toList(growable: false);
